default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  socket: <% %x(mysql_config --socket).chomp %>

development:
  <<: *default
  database: escapism_development

test:
  <<: *default
  database: escapism_test
